import MarkdownIt from 'markdown-it';
import texmath from 'markdown-it-texmath';
import emoji from 'markdown-it-emoji';
import attrs from 'markdown-it-attrs';
import katex from 'katex';
import puppeteer from 'puppeteer-core';
import { spawn } from 'child_process';
import fs from 'fs/promises';
import path from 'path';
import { logger } from './logger.js';

/**
 * Creates and configures the markdown parser.
 * This is the "Brain" of the text processing.
 */
export function createMarkdownParser() {
  const md = new MarkdownIt({
    html: true,
    breaks: true,
    linkify: true,
    typographer: true
  });

  // 1. Math Support: Handles $T_3$ and $$...$$
  // output: 'mathml' is crucial for Pandoc (DOCX) compatibility
  md.use(texmath, {
    engine: katex,
    delimiters: 'dollars',
    katexOptions: { 
        output: 'mathml', 
        throwOnError: false,
        macros: {
          "\\T": "\\text{T}",
          "\\Ca": "\\text{Ca}"
        }
    }
  });

  // 2. Extensions
  md.use(emoji);
  md.use(attrs);

  return md;
}

const parser = createMarkdownParser();

/**
 * Converts Markdown to HTML with injected styles.
 */
export async function markdownToHtml(markdownContent) {
  const bodyHtml = parser.render(markdownContent);
  
  // Styles for PDF rendering via Puppeteer
  const css = `
    <style>
      @font-face { font-family: 'BearSansUI'; src: url('file://${process.cwd()}/assets/fonts/BearSansUI-Regular.woff2'); }
      @font-face { font-family: 'NotoSansSymbols2'; src: url('file://${process.cwd()}/assets/fonts/NotoSansSymbols2-Regular.ttf'); }
      
      body {
        font-family: 'BearSansUI', 'NotoSansSymbols2', sans-serif;
        line-height: 1.6;
        color: #1a1a1a;
        max-width: 800px;
        margin: 0 auto;
        padding: 40px;
      }
      h1, h2, h3 { color: #000; margin-top: 1.5em; }
      table { border-collapse: collapse; width: 100%; margin: 1em 0; }
      th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
      th { background-color: #f5f5f5; }
      code { background: #f0f0f0; padding: 0.2em 0.4em; border-radius: 3px; font-family: monospace; }
      img { max-width: 100%; height: auto; }
      
      /* KaTeX fix for Puppeteer */
      .katex { font-size: 1.1em; }
    </style>
  `;

  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="UTF-8">
      ${css}
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.css">
    </head>
    <body>
      ${bodyHtml}
    </body>
    </html>
  `;
}

/**
 * Converts HTML to DOCX using Pandoc.
 * Pandoc is great at mapping HTML+MathML to Word styles.
 */
export async function htmlToDocx(htmlContent, outputPath) {
  const tempHtmlPath = outputPath + '.html';
  const referenceDoc = path.join(process.cwd(), 'assets', 'reference.docx');
  
  try {
    await fs.writeFile(tempHtmlPath, htmlContent);

    // -f html+mathml tells Pandoc to parse the MathML tags generated by KaTeX
    const args = [
      '-f', 'html+mathml',
      '-t', 'docx',
      '-o', outputPath,
      `--reference-doc=${referenceDoc}`
    ];

    return new Promise((resolve, reject) => {
      const proc = spawn('pandoc', args);
      
      // Feed content via stdin to avoid FS race conditions on the input
      proc.stdin.write(htmlContent);
      proc.stdin.end();

      let stderr = '';
      proc.stderr.on('data', d => stderr += d);

      proc.on('close', (code) => {
        fs.unlink(tempHtmlPath).catch(() => {}); // Cleanup
        if (code === 0) resolve(outputPath);
        else reject(new Error(`Pandoc failed: ${stderr}`));
      });
    });
  } catch (e) {
    throw e;
  }
}

/**
 * Converts HTML to PDF using Puppeteer (Headless Chrome).
 */
export async function htmlToPdf(htmlContent, outputPath) {
  let browser;
  try {
    browser = await puppeteer.launch({
      executablePath: process.env.PUPPETEER_EXECUTABLE_PATH || '/usr/bin/chromium-browser',
      args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
      headless: true
    });

    const page = await browser.newPage();
    await page.setContent(htmlContent, { waitUntil: 'networkidle0' });
    
    await page.pdf({
      path: outputPath,
      format: 'A4',
      printBackground: true,
      margin: { top: '2cm', bottom: '2cm', left: '2cm', right: '2cm' }
    });
  } finally {
    if (browser) await browser.close();
  }
}

/**
 * Unified conversion entry point.
 */
export async function convertMarkdown(input, outputFormat, options = {}) {
    const html = await markdownToHtml(input);
    
    if (outputFormat === 'docx') {
        const outputPath = options.outputPath || `/tmp/${Date.now()}.docx`;
        await htmlToDocx(html, outputPath);
        return outputPath;
    } else if (outputFormat === 'pdf') {
        const outputPath = options.outputPath || `/tmp/${Date.now()}.pdf`;
        await htmlToPdf(html, outputPath);
        return outputPath;
    }
    throw new Error('Unsupported format');
}

// Legacy adapter for JobManager
export async function convertDocument(job) {
    const markdown = await fs.readFile(job.inputPath, 'utf8');
    
    if (job.exportOptions.docx) {
        job.outputs.docx = path.join('/tmp', `output-${job.id}.docx`);
        await convertMarkdown(markdown, 'docx', { outputPath: job.outputs.docx });
    }
    
    if (job.exportOptions.pdf) {
        job.outputs.pdf = path.join('/tmp', `output-${job.id}.pdf`);
        await convertMarkdown(markdown, 'pdf', { outputPath: job.outputs.pdf });
    }
    
    return job.outputs;
}
